version: '2'

volumes:

  lojas-mysql.volume:
    driver: local

services: 

  lojas-apache:
    image: ambientum/php:7.0-apache
    container_name: lojas-apache
    volumes:
      - .:/var/www/app
    ports:
      - "90:8080"

  lojas-mysql:
    image: ambientum/mysql:5.7
    container_name: lojas-mysql.service
    volumes:
      - lojas-mysql.volume:/var/lib/mysql
    ports:
      - "3300:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password